universe                = docker
docker_image            = adv010/misr_tf:v2
executable              = test.py
output                  = pytorch_classifier.$(ClusterId).$(ProcId).out
error                   = pytorch_classifier.$(ClusterId).$(ProcId).err
log                     = pytorch_classifier.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = foldertest/

request_GPUs = 1
request_CPUs = 1
request_memory = 2G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
queue 1

